[tool.poetry]
name = "aoc2020"
version = "1.0.0"
description = "Advent of Code 2020"
authors = ["Csaba Okrona"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
